### ISSUE TITLE
Strange symbols shown instead of notes

### ISSUE THREAD

**Issue by rtaupe** [otfried/ipepresenter-issues#11]
My presentations created with beamer and pdflatex don't work with ipepresenter on Windows.
Instead of the notes, strange symbols are shown:

![ipepresenter_bug](https://github.com/otfried/ipepresenter-issues/assets/1563953/a00d5603-5d68-40be-bc7f-c1635afe09d6)

The issue can be reproduced with the following minimal example, which is also attached:
[test.zip](https://github.com/otfried/ipepresenter-issues/files/14393573/test.zip)

```
\documentclass[aspectratio=169]{beamer}

\title{Test}

\date{2024-02-24}

\usepackage{pdfcomment}
\newcommand{\pdfnote}[1]{\marginnote{\pdfcomment[icon=note]{#1}}}

\begin{document}

\begin{frame}
\titlepage
\end{frame}

\begin{frame}{Hello World}
	Hi!
	\pdfnote{remember to say hello}
\end{frame}

\end{document}
```

**Comment by otfried** [comment]
It turns out your PDF file contains the page labels and the page notes as UTF-16 encoded text.  I had no idea this was actually possible in PDF.  I've updated ipepresenter so it can read this format, so please try the following version.

[ipepresenter-7.2.28-win64.zip](https://github.com/otfried/ipepresenter-issues/files/14396011/ipepresenter-7.2.28-win64.zip)

This will then be in the next release.

**Comment by rtaupe** [comment]
Thank you, this works!
